app:
  name: "web_app"
  mode: "dev"
  port: 8081
  version: "v0.0.1"
  start_time: "2020-07-01"
  machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 1000 #文件大小
  max_backups: 3600 #备份数量
  max_age: 5 #存储时间
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "325523"
  db: "bluebell" #数据库名称
  max_open_conns: 200 #最大连接数
  max_idle_conns: 50 #最大空闲连接数
redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0
  pool_size: 100
  min_idle_conns: 50
